version: 2
updates:
    # Updates for Github Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
          
    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "feature/platform-compliance"
      schedule:
          interval: "monthly"
          
