name: Build JVM Lambda

env:
  JACOCO_DIRECTORY: ${{ inputs.BUILD_DIRECTORY_NAME }}/build/reports/jacoco/test
  PKG_ACTOR: ${{ secrets.PKG_ACTOR }}
  PKG_TOKEN: ${{ secrets.PKG_TOKEN }}

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
      JAVA_DISTRIBUTION:
        required: true
        type: string
      BUILD_DIRECTORY_NAME:
        required: false
        type: string
        default: source
      GRADLE_COMMAND:
        required: false
        type: string
        default: clean build
      JAR_FILE_EXTENSION:
        required: false
        type: string
        default: .jar
jobs:
  build:
    name: Build lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build source lambda
        run: |
          cd ${{ inputs.BUILD_DIRECTORY_NAME }}
          ../gradlew ${{ inputs.GRADLE_COMMAND }}
      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.BUILD_DIRECTORY_NAME }}-build
          path: ${{ inputs.BUILD_DIRECTORY_NAME }}/build/libs/${{ inputs.BUILD_DIRECTORY_NAME }}${{ inputs.JAR_FILE_EXTENSION}}
      - name: Upload jacoco artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.BUILD_DIRECTORY_NAME }}-jacoco
          path: |
            ${{ env.JACOCO_DIRECTORY }}/jacocoTestReport.xml
            ${{ env.JACOCO_DIRECTORY }}/jacocoTestReport.csv
