name: Copy Image between ECRs

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      GITHUB_ROLE_FROM:
        required: true
        type: string
      AWS_REGION_FROM:
        required: false
        type: string
        default: eu-central-1
      AWS_ACCOUNT_ID_FROM:
        required: true
        type: string
      AWS_ECR_URL_FROM:
        required: true
        type: string
      GITHUB_ROLE_TO:
        required: true
        type: string
      AWS_REGION_TO:
        required: false
        type: string
        default: eu-central-1
      AWS_ACCOUNT_ID_TO:
        required: true
        type: string
      AWS_ECR_URL_TO:
        required: true
        type: string
      IMAGE_TAG:
        required: false
        type: string
      TIMEOUT:
        required: false
        type: number
        default: 10

jobs:
  copy-image-between-ecrs:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    steps:
      - uses: actions/checkout@v4

      - name: Determine image tag
        run: |
          PROVIDED_TAG=${{ inputs.IMAGE_TAG }}
          IMAGE_TAG=$($PROVIDED_TAG || git rev-parse --short ${{ github.sha }})
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up AWS credentials - Source
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID_FROM }}:role/${{ inputs.GITHUB_ROLE_FROM }}
          role-session-name: ${{ inputs.GITHUB_ROLE_FROM }}-oidc
          aws-region: ${{ inputs.AWS_REGION_FROM }}

      - name: Login to Amazon ECR - Source
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Pull image from Source ECR
        run: |
          docker pull ${{env.AWS_ECR_URL_FROM}}:${{env.IMAGE_TAG}}

      - name: Tag image with Destination ECR
        run: |
          docker tag ${{env.AWS_ECR_URL_FROM}}:${{env.IMAGE_TAG}} ${{env.AWS_ECR_URL_TO}}:latest
          docker tag ${{env.AWS_ECR_URL_FROM}}:${{env.IMAGE_TAG}} ${{env.AWS_ECR_URL_TO}}:${{env.IMAGE_TAG}}

      - name: Set up AWS credentials - Destination
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID_TO }}:role/${{ inputs.GITHUB_ROLE_TO }}
          role-session-name: ${{ inputs.GITHUB_ROLE_TO }}-oidc
          aws-region: ${{ inputs.AWS_REGION_TO }}

      - name: Login to Amazon ECR - Destination
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image to Destination ECR
        run: |
          docker push ${{env.AWS_ECR_URL_TO}}:${{env.IMAGE_TAG}}
          docker push ${{env.AWS_ECR_URL_TO}}:latest
