name: Stage Deploy

on:
  workflow_call:
    inputs:
      GITHUB_ROLE:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_CLUSTER_NAME:
        required: true
        type: string
      AWS_SERVICE_NAME:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Default Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.GITHUB_ROLE }}
          role-session-name: normalizer-testint-oidc
          aws-region: ${{ inputs.AWS_REGION }}

      - name: AWS ECS - Deploy
        run: aws ecs update-service --force-new-deployment --cluster ${{ inputs.AWS_CLUSTER_NAME }} --service ${{ inputs.AWS_SERVICE_NAME }}
