name: Stage Documentation Test

on:
  workflow_call:
    inputs:
      OPENAPI_DEFINITION_PATH:
        required: false
        type: string

jobs:
  doc-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Default Checkout
        uses: actions/checkout@v3
      - name: Install @redocly/openapi
        run: npm i -g @redocly/cli@latest
      - name: Redocly Lint
        run: redocly lint ${{ inputs.OPENAPI_DEFINITION_PATH || './openapi' }}/openapi.yaml
