name: Stage Documentation

on:
  workflow_call:
    inputs:
      RELEASE_TAG_VERSION:
        required: true
        type: string
      PROJECT_TAG:
        required: true
        type: string
      OPENAPI_DEFINITION_PATH:
        required: false
        type: string
    secrets:
      REDOCLY_AUTHORIZATION:
        required: true

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Default checkout
        uses: actions/checkout@v3
      - name: Install @redocly/cli
        run: npm i -g @redocly/cli@latest
      - name: Documentation push
        run: |
          cd ${{ inputs.OPENAPI_DEFINITION_PATH || './openapi' }}
          redocly bundle external@latest --output dist/external.yaml
          REDOCLY_AUTHORIZATION=${{ secrets.REDOCLY_AUTHORIZATION }} redocly push ./dist/external.yaml "@bettermile/${{ inputs.PROJECT_TAG }}@${{ inputs.RELEASE_TAG_VERSION }}" -u
