name: Stage Documentation

on:
  workflow_call:
    inputs:
      PROJECT_TAG:
        required: true
        type: string
      SOURCE_TAG:
        required: true
        type: string
      DESTINATION_TAG:
        required: false
        description: If not set, SOURCE_TAG will be used as DESTINATION_TAG as well
        type: string
      OPENAPI_DEFINITION_PATH:
        required: false
        type: string
    secrets:
      REDOCLY_AUTHORIZATION:
        required: true

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Default checkout
        uses: actions/checkout@v3
      - name: Install @redocly/cli
        run: npm i -g @redocly/cli@1.7.0
      - name: Documentation push
        run: |
          cd ${{ inputs.OPENAPI_DEFINITION_PATH || './openapi' }}
          redocly bundle ${{ inputs.PROJECT_TAG }}@${{ inputs.SOURCE_TAG }} --output dist/${{ inputs.SOURCE_TAG }}.yaml
          cd dist
          REDOCLY_AUTHORIZATION=${{ secrets.REDOCLY_AUTHORIZATION }} redocly push ./${{ inputs.SOURCE_TAG }}.yaml --organization="bettermile" --destination="${{ inputs.PROJECT_TAG }}@${{ inputs.DESTINATION_TAG || inputs.SOURCE_TAG  }}" -u
