name: Github Packages

on:
  workflow_call:
    secrets:
      PKG_ACTOR:
        required: true
      PKG_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      contents: read
      packages: write
    env:
      PKG_ACTOR: ${{ secrets.PKG_ACTOR }}
      PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew clean build

      - name: Get Release Tag
        id: extract-tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Pversion='${{ steps.extract-tag.outputs.tag }}'
