name: Pulumi Build

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      WORK_DIR:
        required: false
        type: string
        default: './'
    secrets:
      PKG_ACTOR:
        required: false
      PKG_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ inputs.WORK_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build With Credentials
        if: ${{ secrets.PKG_ACTOR != '' }}
        run: PKG_ACTOR=${{ secrets.PKG_ACTOR }} PKG_TOKEN=${{ secrets.PKG_TOKEN }} ./gradlew clean build

      - name: Build Without Credentials
        if: ${{ secrets.PKG_ACTOR == '' }}
        run: ./gradlew clean build
