name: Pulumi Build

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      WORK_DIR:
        required: false
        type: string
        default: './'
    secrets:
      PKG_ACTOR:
        required: false
      PKG_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ inputs.WORK_DIR }}
    env:
      PKG_ACTOR: ${{ secrets.PKG_ACTOR }}
      PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew clean build
