name: Stage S3 Download

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      GITHUB_ROLE:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: false
        type: string
        default: eu-central-1
      SOURCE:
        required: true
        type: string
      DESTINATION:
        required: true
        type: string
      CACHE_PATH:
        required: true
        type: string
      CACHE_KEY:
        required: true
        type: string

jobs:
  s3-down:
    runs-on: ubuntu-20.04
    steps:

      - name: Default Checkout
        uses: actions/checkout@v4

      - name: JDK - Setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Configure AWS Credentials
        if: ${{ inputs.AWS_ACCOUNT_ID != '' }}
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.GITHUB_ROLE }}
          role-session-name: normalizer-testint-oidc
          aws-region: ${{ inputs.AWS_REGION }}

      - name: AWS S3 - Download
        run: aws s3 sync ${{ inputs.SOURCE }} ${{ inputs.DESTINATION }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ inputs.CACHE_PATH }}
          key: ${{ inputs.CACHE_KEY }}
