name: Stage Integration Test

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      TEST_TARGET:
        required: true
        type: string
      SPRING_PROFILE:
        required: true
        type: string
        default: default, test
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PKG_ACTOR:
        required: true
      PKG_TOKEN:
        required: true

jobs:
  test-int:
    runs-on: ubuntu-latest
    steps:
      - name: Default Checkout
        uses: actions/checkout@v3
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: ./src/main/resources/
          key: s3-download
      - name: JDK - Setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: AWS - Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Gradle - Test
        run: PKG_ACTOR=${{ secrets.PKG_ACTOR }} PKG_TOKEN=${{ secrets.PKG_TOKEN }} AWS_REGION=${{ inputs.AWS_REGION }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} ./gradlew test --tests ${{ inputs.TEST_TARGET }} -PtestType=integration -PspringProfile=${{ inputs.SPRING_PROFILE }}
