name: Stage Integration Test
permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      TEST_TARGET:
        required: true
        type: string
      SPRING_PROFILE:
        required: true
        type: string
        default: default, test
      CACHE_PATH:
        required: false
        type: string
      CACHE_KEY:
        required: false
        type: string
      TEST_TYPE:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PKG_ACTOR:
        required: true
      PKG_TOKEN:
        required: true

jobs:
  test-int:
    runs-on: ubuntu-20.04-16-cores
    steps:
      - name: Default Checkout
        uses: actions/checkout@v3
      - name: Cache Primes
        if: ${{ inputs.CACHE_PATH != '' && inputs.CACHE_KEY != '' }}
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: ${{ inputs.CACHE_PATH }}
          key: ${{ inputs.CACHE_KEY }}
      - name: JDK - Setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::336519086291:role/GitHubActionsRole
          role-session-name: normalizer-testint-oidc
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Gradle - Test
        run: PKG_ACTOR=${{ secrets.PKG_ACTOR }} PKG_TOKEN=${{ secrets.PKG_TOKEN }} AWS_REGION=${{ inputs.AWS_REGION }} ./gradlew test --tests ${{ inputs.TEST_TARGET }} -PtestType=${{ inputs.TEST_TYPE || 'integration' }} -PspringProfile=${{ inputs.SPRING_PROFILE }}
