name: Stage Integration Test

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      GITHUB_ROLE:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: false
        type: string
        default: eu-central-1
      TEST_TARGET:
        required: true
        type: string
      SPRING_PROFILE:
        required: false
        type: string
        default: test
      CACHE_PATH:
        required: false
        type: string
      CACHE_KEY:
        required: false
        type: string
      TEST_TYPE:
        required: false
        type: string
        default: integration
    secrets:
      PKG_ACTOR:
        required: true
      PKG_TOKEN:
        required: true

jobs:
  test-int:
    runs-on: ubuntu-20.04
    steps:

      - name: Default Checkout
        uses: actions/checkout@v3

      - name: Cache Primes
        if: ${{ inputs.CACHE_PATH != '' && inputs.CACHE_KEY != '' }}
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: ${{ inputs.CACHE_PATH }}
          key: ${{ inputs.CACHE_KEY }}

      - name: JDK - Setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Configure AWS Credentials
        if: ${{ inputs.AWS_ACCOUNT_ID != '' }}
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.GITHUB_ROLE }}
          role-session-name: ${{ inputs.GITHUB_ROLE }}-oidc
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Gradle - Test
        run: PKG_ACTOR=${{ secrets.PKG_ACTOR }} PKG_TOKEN=${{ secrets.PKG_TOKEN }} AWS_REGION=${{ inputs.AWS_REGION }} ./gradlew test --tests ${{ inputs.TEST_TARGET }} -PtestType=${{ inputs.TEST_TYPE }} -PspringProfile=${{ inputs.SPRING_PROFILE }}
